### ISSUE TITLE
first run error

### ISSUE THREAD

**Issue by xiaosuv** [demon-rem/kodi-strm#5]
(strm) ➜  kodi-strm git:(master) ✗ ./strm-generator.py 
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=tcvsobb1j1i0rpk3.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A53371%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.readonly&state=FUjhTbM4cRWYUTlOndV54f9eY0LK2c&access_type=offline
Traceback (most recent call last):
  File "/Users/bob/Downloads/strm/kodi-strm/./strm-generator.py", line 419, in <module>
    main()
  File "/Users/bob/Downloads/strm/kodi-strm/./strm-generator.py", line 320, in main
    service = authenticate()
  File "/Users/bob/Downloads/strm/kodi-strm/./strm-generator.py", line 57, in authenticate
    creds = flow.run_local_server(port=0)
  File "/Users/bob/Downloads/strm/lib/python3.9/site-packages/google_auth_oauthlib/flow.py", line 458, in run_local_server
    authorization_response = wsgi_app.last_request_uri.replace(
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by demon-rem** [comment]
Hi, sorry for the delay. 

The problem you're facing seems to be related to the `google-auth-oauthlib` package (which is internally being used in this repo). On a quick glance, seems like you're facing [this](https://github.com/googleworkspace/python-samples/issues/88) issue.

Seems like they didn't reach a conclusion. As suggested by a user in the same issue, try [using a different browser](https://github.com/googleworkspace/python-samples/issues/88#issuecomment-696884372) to authenticate the session (or paste URL from the pop-up window to another browser).

**Comment by demon-rem** [comment]
I'm unable to replicate this issue at my end, I doubt I'll be of much help with this. Also, given that this issue isn't directly related to the code from this repository - I'll be closing this issue for now.
