### ISSUE TITLE
Easiest way to implement with Kodi running on Xbox? 

### ISSUE THREAD

**Issue by cboswald95** [demon-rem/kodi-strm#84]
If this is a question outside the scope of this script, feel free to delete / ignore this request, but I'm relatively new to Kodi and have had innumerable issues getting the Google Drive Add-on to reliably export .strm files for monitored folders.  Can I run the script on a separate PC and share the .strm directory to the Xbox via SMB? Could the script run on something like a heroku app and share the .strm files from there as an https source? 

Sorry for what are probably misguided questions, but some documentation on a way to use this script on devices that can't directly run it would be hugely valuable to me and many other kodi users. Thanks for your time :)

**Comment by demon-rem** [comment]
> Can I run the script on a separate PC and share the .strm directory to the Xbox via SMB?

Yep, how or where you run the script to generate `strm` files is irrelevant, as long as you can place the generated files in the correct path in your Xbox - the add-on will be able to parse them. 

Make sure that the google account you login with on your Xbox has access to these files on drive - beyond that, you're good to go! 

And yes, Heroku can work fine as well - as long as you can download those files on your Xbox. If you go ahead with this plan, I recommend zipping the root folder on Heroku, and unzipping it back in your Xbox, depending on the number of files generated, transferring them individually can take quite a lot of time.
